layout_spectrum: 0.5412671266391984
typography_spectrum: 0.5586901856535622
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.08865273261534991
  lightness: 0.2941017476792014
  saturation: 0.7786300681866153
  rhythmicContrast: 0.3118880174352354
github: true
author:
  name: Kristoffer Rose Svarre
  email: ksvarre@gmail.com
  url: 'https://www.linkedin.com/in/ksvarre/'
name: Crypto Economics
url: 'http://crypto.think-like.me/'
navigation:
  - name: Home
    url: 'https://think-like.me'
    type: external
  - name: Technology & Science
    url: 'http://ai.think-like.me/'
    type: external
  - name: 'Business, Innovation & Entrepreneurship'
    url: 'http://business.think-like.me/'
    type: external
  - name: Motivation & Personal Deevlopment
    url: 'http://development.think-like.me/'
    type: external
  - name: Accomplishments & Portfolio
    url: 'http://portfolio.think-like.me/'
    type: external
  - name: About Me
    url: 'https://www.linkedin.com/in/ksvarre'
    type: external
title: Blockchain & Crypto Economics
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/a776dec0899259576fe21e0bc7840217e764e737.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/a776dec0899259576fe21e0bc7840217e764e737.jpg
    metadata:
      datePublished: null
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/696b495d9eac72b23497909b0ead6899/croprotate.jpeg?cropheight=675&cropwidth=892&degrees=0&input=https%3A%2F%2Fvideo-images.vice.com%2Farticles%2F59431309df10a05676b8f847%2Flede%2F1497612065665-shutterstock_653153323.jpeg%3Fcrop%3D1xw%3A0.8364312267657993xh%3Bcenter%2Ccenter%26resize%3D1200%3A*&x=149&y=0
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'http://vice.com'
        name: Vice
        favicon: null
        domain: imgflo.herokuapp.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  in recent months I have devoted an increased amount of time on understanding
  and evangelizing crypto currencies and blockchain technology. on this blog i
  will post about what i learned, and how.
